import { readFileSync } from "node:fs"
import { builtinModules } from "node:module"
import process from "node:process"
import * as esbuild from "esbuild"

const manifest = JSON.parse(readFileSync("manifest.json", "utf8"))
const production = process.argv[2] === "production"

const context = await esbuild.context({
  banner: {
    js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
See the source repository for editable TypeScript.
*/
const PLUGIN_VERSION = ${JSON.stringify(manifest.version)};
`,
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  logLevel: "info",
  outfile: "main.js",
  platform: "browser",
  sourcemap: production ? false : "inline",
  target: "es2022",
})

if (production) {
  await context.rebuild()
  await context.dispose()
} else {
  await context.watch()
}
