/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
See the source repository for editable TypeScript.
*/
const PLUGIN_VERSION = "0.1.0";

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => UnderscoreTitlePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/features/explorer.ts
var import_obsidian2 = require("obsidian");

// src/constants.ts
var TITLE_SOURCE = {
  Delimiter: "delimiter",
  Frontmatter: "frontmatter",
  Original: "original"
};
var ITEM_KIND = {
  File: "file",
  Folder: "folder"
};
var LANGUAGE_MODE = {
  Auto: "auto",
  English: "en",
  Korean: "ko"
};
var SORT_MODE = {
  DisplayTitle: "display-title",
  OriginalName: "original-name"
};

// src/obsidian-internals.ts
var import_obsidian = require("obsidian");
function readExplorerView(view) {
  if (!isRecord(view) || !isRecord(view["fileItems"])) {
    return null;
  }
  return {
    fileItems: view["fileItems"],
    record: view,
    requestSort: readCallable(view["requestSort"]),
    sortOrder: typeof view["sortOrder"] === "string" ? view["sortOrder"] : null
  };
}
function readExplorerItem(item) {
  if (!isRecord(item) || !(item["file"] instanceof import_obsidian.TAbstractFile) || !(item["innerEl"] instanceof HTMLElement)) {
    return null;
  }
  const updateTitle = readCallable(item["updateTitle"]);
  if (updateTitle === null) {
    return null;
  }
  return {
    file: item["file"],
    innerEl: item["innerEl"],
    originalStartRename: readCallable(item["startRename"]),
    originalUpdateTitle: updateTitle,
    record: item
  };
}
function readGraphView(view) {
  if (!isRecord(view) || !isRecord(view["renderer"])) {
    return null;
  }
  const nodes = Array.isArray(view["renderer"]["nodes"]) ? view["renderer"]["nodes"] : [];
  return {
    nodes,
    onIframeLoad: readCallable(view["renderer"]["onIframeLoad"])
  };
}
function readGraphNode(node) {
  if (!isRecord(node) || typeof node["id"] !== "string") {
    return null;
  }
  return { id: node["id"], record: node };
}
function readTabLeaf(leaf) {
  if (!isRecord(leaf) || !isRecord(leaf["view"])) {
    return null;
  }
  const file = leaf["view"]["file"];
  const titleEl = leaf["tabHeaderInnerTitleEl"];
  return file instanceof import_obsidian.TAbstractFile && titleEl instanceof HTMLElement ? { file, titleEl } : null;
}
function readFolderArgument(value) {
  return value instanceof import_obsidian.TFolder ? value : null;
}
function getPrototypeRecord(value) {
  const prototype = Object.getPrototypeOf(value);
  return isRecord(prototype) ? prototype : null;
}
function callMethod(method, thisArg, args = []) {
  return method.apply(thisArg, [...args]);
}
function readCallable(value) {
  return isCallable(value) ? value : null;
}
function isRecord(value) {
  return typeof value === "object" && value !== null;
}
function isCallable(value) {
  return typeof value === "function";
}

// src/features/explorer.ts
var ExplorerFeature = class {
  constructor(getLeaves, getSettings, titleService) {
    this.getLeaves = getLeaves;
    this.getSettings = getSettings;
    this.titleService = titleService;
  }
  getLeaves;
  getSettings;
  titleService;
  itemPatches = /* @__PURE__ */ new WeakMap();
  sortPatches = /* @__PURE__ */ new WeakMap();
  enabled = false;
  enable() {
    this.enabled = true;
    this.refresh();
  }
  disable() {
    this.enabled = false;
    this.restoreItems();
    this.restoreSorts();
  }
  refresh() {
    if (!this.enabled) {
      return;
    }
    for (const view of this.getExplorerViews()) {
      this.patchSort(view);
      for (const item of Object.values(view.fileItems)) {
        this.patchItem(item);
      }
      view.requestSort?.();
    }
  }
  patchItem(item) {
    const state = readExplorerItem(item);
    if (state === null || this.itemPatches.has(state.record)) {
      if (state !== null) {
        state.originalUpdateTitle.call(state.record);
      }
      return;
    }
    const feature = this;
    state.record["updateTitle"] = function updateTitle() {
      state.originalUpdateTitle.call(this);
      feature.applyItemTitle(state);
    };
    if (state.originalStartRename !== null) {
      state.record["startRename"] = function startRename(...args) {
        state.innerEl.textContent = state.file instanceof import_obsidian2.TFile ? state.file.basename : state.file.name;
        return state.originalStartRename?.apply(this, args);
      };
    }
    this.itemPatches.set(state.record, state);
    state.originalUpdateTitle.call(state.record);
    this.applyItemTitle(state);
  }
  applyItemTitle(state) {
    const title = this.titleService.resolveFile(state.file);
    if (title !== null) {
      state.innerEl.textContent = title.title;
    }
  }
  patchSort(view) {
    if (this.getSettings().explorerSort !== SORT_MODE.DisplayTitle) {
      return;
    }
    const original = readSortMethod(view);
    if (original === null || this.sortPatches.has(view.record)) {
      return;
    }
    const feature = this;
    this.sortPatches.set(view.record, {
      hadOwnMethod: Object.hasOwn(view.record, "getSortedFolderItems"),
      original
    });
    view.record["getSortedFolderItems"] = function getSortedFolderItems(...args) {
      const folder = readFolderArgument(args[0]);
      return folder === null ? original.apply(this, args) : feature.sortFolderItems(view, folder, original, this);
    };
  }
  sortFolderItems(view, folder, original, thisArg) {
    const sortOrder = view.sortOrder;
    if (sortOrder !== "alphabetical" && sortOrder !== "alphabeticalReverse") {
      return original.call(thisArg, folder);
    }
    const multiplier = sortOrder === "alphabetical" ? 1 : -1;
    return [...folder.children].filter(isSortableFile).sort((left, right) => this.compareFiles(left, right) * multiplier).map((file) => view.fileItems[file.path]).filter((item) => item !== void 0);
  }
  compareFiles(left, right) {
    if (left instanceof import_obsidian2.TFolder && right instanceof import_obsidian2.TFile) {
      return -1;
    }
    if (left instanceof import_obsidian2.TFile && right instanceof import_obsidian2.TFolder) {
      return 1;
    }
    return this.displayTitle(left).localeCompare(this.displayTitle(right));
  }
  displayTitle(file) {
    return this.titleService.resolveFile(file)?.title ?? (file instanceof import_obsidian2.TFile ? file.basename : file.name);
  }
  getExplorerViews() {
    return this.getLeaves().map((leaf) => readExplorerView(leaf.view)).filter((view) => view !== null);
  }
  restoreItems() {
    for (const view of this.getExplorerViews()) {
      for (const item of Object.values(view.fileItems)) {
        const state = readExplorerItem(item);
        if (state === null || !this.itemPatches.has(state.record)) {
          continue;
        }
        state.record["updateTitle"] = state.originalUpdateTitle;
        if (state.originalStartRename !== null) {
          state.record["startRename"] = state.originalStartRename;
        }
        this.itemPatches.delete(state.record);
        state.originalUpdateTitle.call(state.record);
      }
    }
  }
  restoreSorts() {
    for (const view of this.getExplorerViews()) {
      const patch = this.sortPatches.get(view.record);
      if (patch === void 0) {
        continue;
      }
      if (patch.hadOwnMethod) {
        view.record["getSortedFolderItems"] = patch.original;
      } else {
        delete view.record["getSortedFolderItems"];
      }
      this.sortPatches.delete(view.record);
      view.requestSort?.();
    }
  }
};
function isSortableFile(file) {
  return file instanceof import_obsidian2.TFile || file instanceof import_obsidian2.TFolder;
}
function readSortMethod(view) {
  const own = view.record["getSortedFolderItems"];
  if (isCallable(own)) {
    return own;
  }
  const prototype = getPrototypeRecord(view.record);
  const inherited = prototype?.["getSortedFolderItems"];
  return isCallable(inherited) ? inherited : null;
}

// src/features/graph.ts
var GraphFeature = class {
  constructor(getLeaves, titleService) {
    this.getLeaves = getLeaves;
    this.titleService = titleService;
  }
  getLeaves;
  titleService;
  patch = null;
  enabled = false;
  enable() {
    this.enabled = true;
    this.refresh();
  }
  disable() {
    this.enabled = false;
    if (this.patch !== null) {
      this.patch.prototype["getDisplayText"] = this.patch.original;
      this.patch = null;
    }
  }
  refresh() {
    if (!this.enabled) {
      return;
    }
    this.patchGraphNodePrototype();
    for (const view of this.getGraphViews()) {
      view.onIframeLoad?.();
    }
  }
  patchGraphNodePrototype() {
    if (this.patch !== null) {
      return;
    }
    const node = this.getGraphViews().flatMap((view) => view.nodes).map(readGraphNode).find(isPresent);
    if (node === void 0) {
      return;
    }
    const prototype = getPrototypeRecord(node.record);
    const original = prototype?.["getDisplayText"];
    if (prototype === null || !isCallable(original)) {
      return;
    }
    const service = this.titleService;
    prototype["getDisplayText"] = function getDisplayText(...args) {
      const current = readGraphNode(this);
      if (current !== null) {
        const title = service.resolvePath(current.id);
        if (title !== null) {
          return title.title;
        }
      }
      return callMethod(original, this, args);
    };
    this.patch = { original, prototype };
  }
  getGraphViews() {
    return this.getLeaves().map((leaf) => readGraphView(leaf.view)).filter((view) => view !== null);
  }
};
function isPresent(value) {
  return value !== null;
}

// src/features/tabs.ts
var import_obsidian3 = require("obsidian");
var TabsFeature = class {
  constructor(getLeaves, titleService) {
    this.getLeaves = getLeaves;
    this.titleService = titleService;
  }
  getLeaves;
  titleService;
  enabled = false;
  enable() {
    this.enabled = true;
    this.refresh();
  }
  disable() {
    this.enabled = false;
    this.refresh();
  }
  refresh() {
    for (const leaf of this.getLeaves()) {
      const tab = readTabLeaf(leaf);
      if (tab === null) {
        continue;
      }
      const title = this.enabled ? this.titleService.resolveFile(tab.file) : null;
      tab.titleEl.textContent = title?.title ?? (tab.file instanceof import_obsidian3.TFile ? tab.file.basename : tab.file.name);
    }
  }
};

// src/features/coordinator.ts
var FeatureCoordinator = class {
  explorer;
  graph;
  tabs;
  constructor(getLeavesOfType, getSettings, titleService) {
    this.explorer = new ExplorerFeature(
      () => getLeavesOfType("file-explorer"),
      getSettings,
      titleService
    );
    this.graph = new GraphFeature(
      () => [...getLeavesOfType("graph"), ...getLeavesOfType("localgraph")],
      titleService
    );
    this.tabs = new TabsFeature(() => getLeavesOfType("markdown"), titleService);
  }
  apply(settings) {
    settings.features.explorer ? this.explorer.enable() : this.explorer.disable();
    settings.features.graph ? this.graph.enable() : this.graph.disable();
    settings.features.tabs ? this.tabs.enable() : this.tabs.disable();
  }
  refresh() {
    this.explorer.refresh();
    this.graph.refresh();
    this.tabs.refresh();
  }
  disable() {
    this.explorer.disable();
    this.graph.disable();
    this.tabs.disable();
  }
};

// src/i18n.ts
var import_obsidian4 = require("obsidian");
var EN = {
  "command.refresh": "Refresh displayed titles",
  "settings.debug.desc": "Log refresh decisions to the developer console.",
  "settings.debug.name": "Debug mode",
  "settings.delimiter.desc": "Text before this separator is hidden in file and folder titles.",
  "settings.delimiter.name": "Delimiter",
  "settings.explorer.desc": "Apply display titles to the file explorer.",
  "settings.explorer.name": "File explorer",
  "settings.graph.desc": "Apply display titles to graph and local graph nodes.",
  "settings.graph.name": "Graph",
  "settings.group.features": "Scopes",
  "settings.group.rules": "Path rules",
  "settings.group.title": "Title resolving",
  "settings.ignore.desc": "One glob per line. Matching paths are never changed.",
  "settings.ignore.name": "Ignore rules",
  "settings.include.desc": "One glob per line. Leave empty to include every path.",
  "settings.include.name": "Include rules",
  "settings.language.desc": "Automatic uses Obsidian's current locale.",
  "settings.language.name": "Language",
  "settings.language.option.auto": "Automatic",
  "settings.language.option.en": "English",
  "settings.language.option.ko": "Korean",
  "settings.preview.frontmatter.desc": "Optional frontmatter title used by the preview.",
  "settings.preview.frontmatter.name": "Preview frontmatter title",
  "settings.preview.name.desc": "A file or folder basename to preview.",
  "settings.preview.name.name": "Preview name",
  "settings.preview.result": "Preview result",
  "settings.preview.source": "Source",
  "settings.search.desc": "Reserved for search and suggest surfaces.",
  "settings.search.name": "Search and suggest",
  "settings.sort.desc": "Choose how files are sorted when Explorer scope is enabled.",
  "settings.sort.name": "Explorer sorting",
  "settings.sort.option.display": "Displayed title",
  "settings.sort.option.original": "Original filename",
  "settings.tabs.desc": "Apply display titles to markdown tab headers.",
  "settings.tabs.name": "Tabs",
  "settings.titleKey.desc": "Frontmatter key that overrides delimiter titles for files.",
  "settings.titleKey.name": "Frontmatter title key"
};
var KO = {
  "command.refresh": "\uD45C\uC2DC \uC81C\uBAA9 \uC0C8\uB85C\uACE0\uCE68",
  "settings.debug.desc": "\uAC1C\uBC1C\uC790 \uCF58\uC194\uC5D0 \uC0C8\uB85C\uACE0\uCE68 \uACB0\uC815\uC744 \uAE30\uB85D\uD569\uB2C8\uB2E4.",
  "settings.debug.name": "\uB514\uBC84\uADF8 \uBAA8\uB4DC",
  "settings.delimiter.desc": "\uD30C\uC77C/\uD3F4\uB354 \uC81C\uBAA9\uC5D0\uC11C \uC774 \uAD6C\uBD84\uC790 \uC55E\uC758 \uD14D\uC2A4\uD2B8\uB97C \uC228\uAE41\uB2C8\uB2E4.",
  "settings.delimiter.name": "\uAD6C\uBD84\uC790",
  "settings.explorer.desc": "\uD30C\uC77C \uD0D0\uC0C9\uAE30\uC5D0 \uD45C\uC2DC \uC81C\uBAA9\uC744 \uC801\uC6A9\uD569\uB2C8\uB2E4.",
  "settings.explorer.name": "\uD30C\uC77C \uD0D0\uC0C9\uAE30",
  "settings.graph.desc": "\uADF8\uB798\uD504\uC640 \uB85C\uCEEC \uADF8\uB798\uD504 \uB178\uB4DC\uC5D0 \uD45C\uC2DC \uC81C\uBAA9\uC744 \uC801\uC6A9\uD569\uB2C8\uB2E4.",
  "settings.graph.name": "\uADF8\uB798\uD504",
  "settings.group.features": "\uC801\uC6A9 \uBC94\uC704",
  "settings.group.rules": "\uACBD\uB85C \uADDC\uCE59",
  "settings.group.title": "\uC81C\uBAA9 \uD574\uC11D",
  "settings.ignore.desc": "\uD55C \uC904\uC5D0 glob \uD558\uB098\uC529 \uC785\uB825\uD569\uB2C8\uB2E4. \uC77C\uCE58\uD55C \uACBD\uB85C\uB294 \uD56D\uC0C1 \uC81C\uC678\uB429\uB2C8\uB2E4.",
  "settings.ignore.name": "\uBB34\uC2DC \uADDC\uCE59",
  "settings.include.desc": "\uD55C \uC904\uC5D0 glob \uD558\uB098\uC529 \uC785\uB825\uD569\uB2C8\uB2E4. \uBE44\uC6CC\uB450\uBA74 \uC804\uCCB4 \uACBD\uB85C\uB97C \uD3EC\uD568\uD569\uB2C8\uB2E4.",
  "settings.include.name": "\uD3EC\uD568 \uADDC\uCE59",
  "settings.language.desc": "\uC790\uB3D9\uC740 Obsidian\uC758 \uD604\uC7AC \uC5B8\uC5B4\uB97C \uC0AC\uC6A9\uD569\uB2C8\uB2E4.",
  "settings.language.name": "\uC5B8\uC5B4",
  "settings.language.option.auto": "\uC790\uB3D9",
  "settings.language.option.en": "\uC601\uC5B4",
  "settings.language.option.ko": "\uD55C\uAD6D\uC5B4",
  "settings.preview.frontmatter.desc": "\uBBF8\uB9AC\uBCF4\uAE30\uC5D0 \uC0AC\uC6A9\uD560 \uC120\uD0DD\uC801 frontmatter \uC81C\uBAA9\uC785\uB2C8\uB2E4.",
  "settings.preview.frontmatter.name": "\uBBF8\uB9AC\uBCF4\uAE30 frontmatter \uC81C\uBAA9",
  "settings.preview.name.desc": "\uBBF8\uB9AC\uBCFC \uD30C\uC77C \uB610\uB294 \uD3F4\uB354 basename\uC785\uB2C8\uB2E4.",
  "settings.preview.name.name": "\uBBF8\uB9AC\uBCF4\uAE30 \uC774\uB984",
  "settings.preview.result": "\uBBF8\uB9AC\uBCF4\uAE30 \uACB0\uACFC",
  "settings.preview.source": "\uCD9C\uCC98",
  "settings.search.desc": "\uAC80\uC0C9\uACFC \uC81C\uC548 UI \uC801\uC6A9\uC744 \uC704\uD55C \uC608\uC57D \uC124\uC815\uC785\uB2C8\uB2E4.",
  "settings.search.name": "\uAC80\uC0C9\uACFC \uC81C\uC548",
  "settings.sort.desc": "Explorer \uC801\uC6A9 \uC2DC \uD30C\uC77C \uC815\uB82C \uAE30\uC900\uC744 \uC120\uD0DD\uD569\uB2C8\uB2E4.",
  "settings.sort.name": "Explorer \uC815\uB82C",
  "settings.sort.option.display": "\uD45C\uC2DC \uC81C\uBAA9",
  "settings.sort.option.original": "\uC6D0\uB798 \uD30C\uC77C\uBA85",
  "settings.tabs.desc": "\uB9C8\uD06C\uB2E4\uC6B4 \uD0ED \uD5E4\uB354\uC5D0 \uD45C\uC2DC \uC81C\uBAA9\uC744 \uC801\uC6A9\uD569\uB2C8\uB2E4.",
  "settings.tabs.name": "\uD0ED",
  "settings.titleKey.desc": "\uD30C\uC77C\uC5D0\uC11C \uAD6C\uBD84\uC790 \uC81C\uBAA9\uBCF4\uB2E4 \uC6B0\uC120\uD560 frontmatter \uD0A4\uC785\uB2C8\uB2E4.",
  "settings.titleKey.name": "Frontmatter \uC81C\uBAA9 \uD0A4"
};
function createTranslator(language) {
  const resolved = language === LANGUAGE_MODE.Auto ? resolveAutomaticLanguage() : language;
  const messages = resolved === LANGUAGE_MODE.Korean ? KO : EN;
  return (key) => messages[key] ?? EN[key];
}
function resolveAutomaticLanguage() {
  return import_obsidian4.moment.locale().toLowerCase().startsWith("ko") ? LANGUAGE_MODE.Korean : LANGUAGE_MODE.English;
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  debug: false,
  delimiter: "__",
  explorerSort: SORT_MODE.OriginalName,
  features: {
    explorer: true,
    graph: true,
    search: false,
    tabs: true
  },
  ignoreRules: [],
  includeRules: [],
  language: LANGUAGE_MODE.Auto,
  previewFrontmatterTitle: "",
  previewName: "20260619__Meeting note",
  titleKey: "title"
};
function parseSettings(value) {
  if (!isRecord2(value)) {
    return DEFAULT_SETTINGS;
  }
  const settings = {};
  put(settings, "debug", readBoolean(value, "debug"));
  put(settings, "delimiter", readString(value, "delimiter"));
  put(settings, "explorerSort", readSortMode(value["explorerSort"]));
  put(settings, "features", readFeatureSettings(value["features"]));
  put(settings, "ignoreRules", readStringArray(value["ignoreRules"]));
  put(settings, "includeRules", readStringArray(value["includeRules"]));
  put(settings, "language", readLanguageMode(value["language"]));
  put(settings, "previewFrontmatterTitle", readString(value, "previewFrontmatterTitle"));
  put(settings, "previewName", readString(value, "previewName"));
  put(settings, "titleKey", readString(value, "titleKey"));
  return normalizeSettings(settings);
}
function normalizeSettings(input) {
  return {
    ...DEFAULT_SETTINGS,
    ...input,
    delimiter: input.delimiter?.length ? input.delimiter : DEFAULT_SETTINGS.delimiter,
    features: {
      ...DEFAULT_SETTINGS.features,
      ...input.features
    },
    ignoreRules: input.ignoreRules ?? DEFAULT_SETTINGS.ignoreRules,
    includeRules: input.includeRules ?? DEFAULT_SETTINGS.includeRules,
    titleKey: input.titleKey?.trim() || DEFAULT_SETTINGS.titleKey
  };
}
function isRecord2(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function readBoolean(record, key) {
  const value = record[key];
  return typeof value === "boolean" ? value : void 0;
}
function readString(record, key) {
  const value = record[key];
  return typeof value === "string" ? value : void 0;
}
function readStringArray(value) {
  return Array.isArray(value) && value.every((item) => typeof item === "string") ? value : void 0;
}
function readFeatureSettings(value) {
  if (!isRecord2(value)) {
    return void 0;
  }
  const features = {};
  put(features, "explorer", typeof value["explorer"] === "boolean" ? value["explorer"] : void 0);
  put(features, "graph", typeof value["graph"] === "boolean" ? value["graph"] : void 0);
  put(features, "search", typeof value["search"] === "boolean" ? value["search"] : void 0);
  put(features, "tabs", typeof value["tabs"] === "boolean" ? value["tabs"] : void 0);
  return features;
}
function readLanguageMode(value) {
  return value === LANGUAGE_MODE.Auto || value === LANGUAGE_MODE.English || value === LANGUAGE_MODE.Korean ? value : void 0;
}
function readSortMode(value) {
  return value === SORT_MODE.DisplayTitle || value === SORT_MODE.OriginalName ? value : void 0;
}
function put(record, key, value) {
  if (value !== void 0) {
    record[key] = value;
  }
}

// src/settings-tab.ts
var import_obsidian5 = require("obsidian");

// src/settings-bindings.ts
function textSetting(key, name, desc) {
  return {
    control: {
      key,
      type: "text",
      validate: (value) => value.trim().length === 0 ? "Required." : void 0
    },
    desc,
    name
  };
}
function toggleSetting(key, name, desc) {
  return {
    control: {
      key,
      type: "toggle"
    },
    desc,
    name
  };
}
function updateSetting(settings, key, value) {
  switch (key) {
    case "debug":
      return typeof value === "boolean" ? { ...settings, debug: value } : settings;
    case "delimiter":
      return typeof value === "string" && value.length > 0 ? { ...settings, delimiter: value } : settings;
    case "explorerSort":
      return value === SORT_MODE.DisplayTitle || value === SORT_MODE.OriginalName ? { ...settings, explorerSort: value } : settings;
    case "features.explorer":
    case "features.graph":
    case "features.tabs":
      return typeof value === "boolean" ? updateFeature(settings, key, value) : settings;
    case "language":
      return value === LANGUAGE_MODE.Auto || value === LANGUAGE_MODE.English || value === LANGUAGE_MODE.Korean ? { ...settings, language: value } : settings;
    case "previewFrontmatterTitle":
      return typeof value === "string" ? { ...settings, previewFrontmatterTitle: value } : settings;
    case "previewName":
      return typeof value === "string" && value.length > 0 ? { ...settings, previewName: value } : settings;
    case "titleKey":
      return typeof value === "string" && value.trim().length > 0 ? { ...settings, titleKey: value.trim() } : settings;
    default:
      return settings;
  }
}
function splitRules(value) {
  return value.split("\n").map((rule) => rule.trim()).filter((rule) => rule.length > 0);
}
function updateFeature(settings, key, value) {
  switch (key) {
    case "features.explorer":
      return { ...settings, features: { ...settings.features, explorer: value } };
    case "features.graph":
      return { ...settings, features: { ...settings.features, graph: value } };
    case "features.tabs":
      return { ...settings, features: { ...settings.features, tabs: value } };
  }
}

// src/title-resolver.ts
function resolveDisplayTitle(input) {
  const frontmatterTitle = input.kind === ITEM_KIND.File ? getFrontmatterTitle(input) : null;
  if (frontmatterTitle !== null) {
    return { source: TITLE_SOURCE.Frontmatter, title: frontmatterTitle };
  }
  const delimiterTitle = getDelimiterTitle(input.basename, input.delimiter);
  if (delimiterTitle !== null) {
    return { source: TITLE_SOURCE.Delimiter, title: delimiterTitle };
  }
  return { source: TITLE_SOURCE.Original, title: input.basename };
}
function getFrontmatterTitle(input) {
  const raw = input.frontmatter?.[input.titleKey];
  return coerceTitleValue(raw);
}
function getDelimiterTitle(basename, delimiter) {
  if (delimiter.length === 0) {
    return null;
  }
  const delimiterIndex = basename.indexOf(delimiter);
  if (delimiterIndex < 0) {
    return null;
  }
  const title = basename.slice(delimiterIndex + delimiter.length).trim();
  return title.length > 0 ? title : null;
}
function coerceTitleValue(value) {
  if (typeof value === "string") {
    const trimmed = value.trim();
    return trimmed.length > 0 ? trimmed : null;
  }
  if (typeof value === "number" && Number.isFinite(value)) {
    return String(value);
  }
  if (Array.isArray(value)) {
    for (const item of value) {
      const title = coerceTitleValue(item);
      if (title !== null) {
        return title;
      }
    }
  }
  return null;
}

// src/settings-tab.ts
var UnderscoreTitleSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, host) {
    super(app, host);
    this.host = host;
  }
  host;
  getSettingDefinitions() {
    const t = this.host.t;
    return [
      {
        heading: t("settings.group.title"),
        items: [
          textSetting("delimiter", t("settings.delimiter.name"), t("settings.delimiter.desc")),
          textSetting("titleKey", t("settings.titleKey.name"), t("settings.titleKey.desc")),
          {
            name: t("settings.language.name"),
            desc: t("settings.language.desc"),
            control: {
              defaultValue: LANGUAGE_MODE.Auto,
              key: "language",
              options: {
                [LANGUAGE_MODE.Auto]: t("settings.language.option.auto"),
                [LANGUAGE_MODE.English]: t("settings.language.option.en"),
                [LANGUAGE_MODE.Korean]: t("settings.language.option.ko")
              },
              type: "dropdown"
            }
          },
          textSetting(
            "previewName",
            t("settings.preview.name.name"),
            t("settings.preview.name.desc")
          ),
          textSetting(
            "previewFrontmatterTitle",
            t("settings.preview.frontmatter.name"),
            t("settings.preview.frontmatter.desc")
          ),
          this.previewDefinition()
        ],
        type: "group"
      },
      {
        heading: t("settings.group.features"),
        items: [
          toggleSetting(
            "features.explorer",
            t("settings.explorer.name"),
            t("settings.explorer.desc")
          ),
          {
            name: t("settings.sort.name"),
            desc: t("settings.sort.desc"),
            control: {
              defaultValue: SORT_MODE.OriginalName,
              key: "explorerSort",
              options: {
                [SORT_MODE.OriginalName]: t("settings.sort.option.original"),
                [SORT_MODE.DisplayTitle]: t("settings.sort.option.display")
              },
              type: "dropdown"
            }
          },
          toggleSetting("features.graph", t("settings.graph.name"), t("settings.graph.desc")),
          toggleSetting("features.tabs", t("settings.tabs.name"), t("settings.tabs.desc")),
          toggleSetting("debug", t("settings.debug.name"), t("settings.debug.desc"))
        ],
        type: "group"
      },
      {
        heading: t("settings.group.rules"),
        items: [
          this.rulesDefinition(
            "includeRules",
            t("settings.include.name"),
            t("settings.include.desc")
          ),
          this.rulesDefinition("ignoreRules", t("settings.ignore.name"), t("settings.ignore.desc"))
        ],
        type: "group"
      }
    ];
  }
  getControlValue(key) {
    const settings = this.host.getSettings();
    switch (key) {
      case "debug":
        return settings.debug;
      case "delimiter":
        return settings.delimiter;
      case "explorerSort":
        return settings.explorerSort;
      case "features.explorer":
        return settings.features.explorer;
      case "features.graph":
        return settings.features.graph;
      case "features.tabs":
        return settings.features.tabs;
      case "language":
        return settings.language;
      case "previewFrontmatterTitle":
        return settings.previewFrontmatterTitle;
      case "previewName":
        return settings.previewName;
      case "titleKey":
        return settings.titleKey;
      default:
        return void 0;
    }
  }
  async setControlValue(key, value) {
    const settings = this.host.getSettings();
    const next = updateSetting(settings, key, value);
    await this.host.updateSettings(next);
    this.update();
  }
  previewDefinition() {
    const t = this.host.t;
    return {
      name: t("settings.preview.result"),
      render: (setting) => {
        const settings = this.host.getSettings();
        const frontmatterTitle = settings.previewFrontmatterTitle.trim();
        const result = resolveDisplayTitle({
          basename: settings.previewName,
          delimiter: settings.delimiter,
          frontmatter: frontmatterTitle.length > 0 ? { [settings.titleKey]: frontmatterTitle } : void 0,
          kind: ITEM_KIND.File,
          titleKey: settings.titleKey
        });
        setting.setDesc(`${t("settings.preview.source")}: ${result.source}`);
        setting.controlEl.createEl("code", { text: result.title });
      }
    };
  }
  rulesDefinition(key, name, desc) {
    return {
      desc,
      name,
      render: (setting) => {
        const settings = this.host.getSettings();
        setting.addTextArea((text) => {
          text.inputEl.rows = 5;
          text.setPlaceholder("Projects/**").setValue(settings[key].join("\n")).onChange(async (value) => {
            await this.host.updateSettings({ ...settings, [key]: splitRules(value) });
          });
        });
      }
    };
  }
};

// src/title-service.ts
var import_obsidian6 = require("obsidian");

// src/path-rules.ts
function evaluatePathRules(path, rules) {
  const ignoreRule = findMatchingRule(path, rules.ignore);
  if (ignoreRule !== null) {
    return { kind: "ignored", rule: ignoreRule };
  }
  if (rules.include.length === 0) {
    return { kind: "included", rule: null };
  }
  const includeRule = findMatchingRule(path, rules.include);
  return includeRule !== null ? { kind: "included", rule: includeRule } : { kind: "excluded_by_include", rule: null };
}
function isPathAllowed(path, rules) {
  return evaluatePathRules(path, rules).kind === "included";
}
function findMatchingRule(path, rules) {
  for (const rawRule of rules) {
    const rule = rawRule.trim();
    if (rule.length > 0 && globMatches(path, rule)) {
      return rule;
    }
  }
  return null;
}
function globMatches(path, glob) {
  const pattern = glob.split("/").map((segment) => {
    if (segment === "**") {
      return "(?:[^/]+/)*[^/]*";
    }
    return escapeRegExp(segment).replaceAll("\\*", "[^/]*").replaceAll("\\?", "[^/]");
  }).join("/");
  return new RegExp(`^${pattern}$`).test(path);
}
function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// src/title-service.ts
var TitleService = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
  }
  app;
  getSettings;
  resolveFile(file) {
    const settings = this.getSettings();
    if (!isPathAllowed(file.path, {
      ignore: settings.ignoreRules,
      include: settings.includeRules
    })) {
      return null;
    }
    if (file instanceof import_obsidian6.TFile) {
      const cache = this.app.metadataCache.getFileCache(file);
      const frontmatter = isRecord3(cache?.frontmatter) ? cache.frontmatter : void 0;
      return resolveDisplayTitle({
        basename: file.basename,
        delimiter: settings.delimiter,
        frontmatter,
        kind: ITEM_KIND.File,
        titleKey: settings.titleKey
      });
    }
    if (file instanceof import_obsidian6.TFolder) {
      return resolveDisplayTitle({
        basename: file.name,
        delimiter: settings.delimiter,
        kind: ITEM_KIND.Folder,
        titleKey: settings.titleKey
      });
    }
    return null;
  }
  resolvePath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    return file === null ? null : this.resolveFile(file);
  }
};
function isRecord3(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

// src/main.ts
var UnderscoreTitlePlugin = class extends import_obsidian7.Plugin {
  settings = DEFAULT_SETTINGS;
  t = createTranslator(DEFAULT_SETTINGS.language);
  coordinator = null;
  async onload() {
    await this.loadSettings();
    const titleService = new TitleService(this.app, () => this.settings);
    this.coordinator = new FeatureCoordinator(
      (type) => this.app.workspace.getLeavesOfType(type),
      () => this.settings,
      titleService
    );
    this.addSettingTab(new UnderscoreTitleSettingTab(this.app, this));
    this.addCommand({
      callback: () => {
        this.refresh();
        new import_obsidian7.Notice(this.t("command.refresh"));
      },
      id: "refresh-displayed-titles",
      name: this.t("command.refresh")
    });
    this.registerEvents();
    this.app.workspace.onLayoutReady(() => {
      this.coordinator?.apply(this.settings);
    });
  }
  onunload() {
    this.coordinator?.disable();
  }
  getSettings() {
    return this.settings;
  }
  async updateSettings(settings) {
    this.settings = settings;
    this.t = createTranslator(settings.language);
    await this.saveData(settings);
    this.coordinator?.apply(settings);
    this.refresh();
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = parseSettings(loaded);
    this.t = createTranslator(this.settings.language);
    await this.saveData(this.settings);
  }
  registerEvents() {
    this.registerEvent(this.app.workspace.on("layout-change", () => this.refresh()));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.refresh()));
    this.registerEvent(this.app.metadataCache.on("changed", () => this.refresh()));
    this.registerEvent(this.app.vault.on("rename", () => this.refresh()));
  }
  refresh() {
    if (this.settings.debug) {
      console.debug("[underscore-title] refresh displayed titles");
    }
    this.coordinator?.refresh();
  }
};
